name: Check
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**/*.ts'
      - 'src/**/*.tsx'
      - '.eslintrc.js'
      - '.github/workflows/lint.yml'
jobs:
  check:
    name: run check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npm run check
      - run: npm run build

