name: Release
on:
  push:
    tags:
      - v*.*.*
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/package-lock.json') }}
      - uses: docker/login-action@v1
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.ARTIFACT_REPOSITORY_KEY }}
      - name: Set TAG env
        run: echo "TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            asia-northeast1-docker.pkg.dev/cpctf-338715/system/visualizer:latest
            asia-northeast1-docker.pkg.dev/cpctf-338715/system/visualizer:${{env.TAG}}
  deploy-server:
    name: deploy-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/package-lock.json') }}
      - uses: docker/login-action@v1
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.ARTIFACT_REPOSITORY_KEY }}
      - name: Set TAG env
        run: echo "TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          platforms: linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
            asia-northeast1-docker.pkg.dev/cpctf-338715/system/visualizer-server:latest
            asia-northeast1-docker.pkg.dev/cpctf-338715/system/visualizer-server:${{env.TAG}}

